markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Jin Xin's Blog
host: jinxin.info
desc: code notes of Jin Xin

custom:
    category:
        thinking: Thinking
        experience: Experience
        discovery: Discovery
        criticism: Criticism
    categories:
      - name:  thinking
        title: Thinking

      - name:  experience
        title: Experience

      - name:  discovery
        title: Discovery

      - name:  criticism
        title: Criticism

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Jin Xin
        email: admin@jinxin.info
        disqus: tech-justlog-me                     # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: jinxinsdu                           # GitHub账号
        gravatar: 00000000000000000000000000000000  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
